-- 데이터베이스 및 사용자 권한 설정
GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO '${DB_USER}'@'%';
GRANT PROCESS, RELOAD, LOCK TABLES, REPLICATION CLIENT ON *.* TO '${DB_USER}'@'%';

-- DataGrip에서 덤프 및 업로드 허용
GRANT FILE ON *.* TO '${DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, SHOW VIEW, CREATE TEMPORARY TABLES ON `${DB_NAME}`.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;