export type ReservationContentType = {
  eventName?: string | null;
  recurrenceRule?: string | null;
  contents?: string | null;
  organizationName?: string | null;
  teamMember?: string[] | null;
  number?: string | null;
  desk?: string | null;
  food?: string | null;
  chair?: string | null;
  lobby?: string[] | null;
  equipment?: string[] | null;
  rehersalTo?: string | null;
  innerNumber?: number | null;
  outerNumber?: number | null;
  eventPurpose?: string | null;
  rehersalFrom?: string | null;
  rehersalLastdayTo?: string | null;
  rehersalLastdayFrom?: string | null;
};
